# Manually triggered workflow for creating an Indigo deployment release
name: Release for Indigo

on:
  workflow_dispatch:
    inputs:
      release_num:
        description: 'Version Number'
        default: ''
        required: true
      is_prerelease:
        description: 'Pre-Release?'
        default: false
        required: true

jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Install Zip Archiver
      uses: montudor/action-zip@v1

    - name: Zip Plugin Artifact
      run: zip -qq -r "Plex Media Server Manager.indigoPlugin.zip "Plex Media Server Manager.indigoPlugin"
      working-directory: src

    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.event.inputs.release_num }}
        artifacts: "src/Dayton Audio Controller.indigoPlugin.zip"
        body: "Release"
        prerelease: ${{ github.event.inputs.is_prerelease }}
